### ISSUE TITLE
Improve SEO

### ISSUE THREAD

**Issue by RafaelGoulartB** [RafaelGoulartB/freelancer#11]
## Description
Setup all the necessary tools to improve the website search engine optimation.

## Tasks
- [x] Read the following resources:
  - https://snipcart.com/blog/react-seo-nextjs-tutorial
  - https://snipcart.com/spa-seo
  - https://blog.logrocket.com/5-tricks-to-eliminate-render-blocking-resources/

- [x] Install and setup https://github.com/garmeeh/next-seo

- [x] Serve fonts locally using woff and woff2 formats. https://google-webfonts-helper.herokuapp.com/fonts

- [x] Define open graph tags to increase social shareability of content.

- [x] Sitemap to help bots to index the website.

- [x] `robots.txt` to tell the search engines which pages or files the crawler can or can't request from your site.

**Comment by RafaelGoulartB** [comment]
To serve fonts locally, you need to use compressed formats like woff or woff2.

This tool https://google-webfonts-helper.herokuapp.com/fonts help to get the fonts and generate the font-face
